### ISSUE TITLE
epdfinfo server quit unexpectedly

### ISSUE THREAD

**Issue by vikram-mandyam** [vedang/pdf-tools#100]
When I try to open the pdf in `/test/test.pdf`. I get this error  `The epdfinfo server quit.`
On debugging stack trace: 
```emacs-lisp
Debugger entered--Lisp error: (error "The epdfinfo server quit unexpectedly")
  error("The epdfinfo server quit unexpectedly")
  pdf-info-query(renderpage "/Users/vm/Downloads/test.pdf" 1 2518)
  pdf-info-renderpage(1 2518)
  pdf-cache-renderpage(1 2518 2518)
  pdf-view-create-page(1 #<window 3 on test.pdf>)
  pdf-view-display-page(1 #<window 3 on test.pdf>)
  pdf-view-redisplay(#<window 3 on test.pdf>)
  pdf-view-goto-page(1)
  pdf-view-new-window-function((#<window 3 on test.pdf> (needs-redisplay) (page . 1) (overlay . #<overlay from 1 to 102223 in test.pdf>)))
  image-mode-winprops(nil t)
  image-mode-reapply-winprops()
 
```

When I run the same command on terminal: 
```sh
echo renderpage:/Users/vm/Downloads/test.pdf:1:2518 | <path-to-pdf-tools>/server/epdfinfo
```
I get the following: 
```
[1]    18451 done                      echo renderpage:/Users/vmandyam/Downloads/test.pdf:1:2518 | 
       18452 floating point exception  

```

I am running on macOS, Emacs 28.1 and `pdf-tools-20220426.235`

Others: 
```sh
brew info poppler       
poppler: stable 22.02.0 (bottled), HEAD
PDF rendering library (based on the xpdf-3.0 code base)


brew info pkg-config
pkg-config: stable 0.29.2 (bottled)
Manage compile and link flags for libraries

brew info pkg-config
pkg-config: stable 0.29.2 (bottled)
Manage compile and link flags for libraries

brew info cairo    
cairo: stable 1.16.0 (bottled), HEAD
Vector graphics library with cross-device output support
```

**Comment by vikram-mandyam** [comment]
Any updates on this issue? @vedang

**Comment by vikram-mandyam** [comment]
After searching for solutions, it seems this [https://stackoverflow.com/a/73188343/340286](url) does the trick...

**Comment by winterNan** [comment]
I have the same issue. And this is what *message* buffer shows

pdf-info-query: The epdfinfo server quit unexpectedlyError during redisplay: (eval (pdf-misc-size-indication)) signaled (error "Invalid image specification: nil")

I also tried the link above but to no avail.

**Comment by winterNan** [comment]
I have a similar problem and I can confirm that the above solution does not work. Is there any solution yet for the bug?

**Comment by vedang** [comment]
@winterNan @vikram-mandyam : Can one of you please re-file this bug using the new bug template? It has instructions on capturing details like OS version and Emacs version which I think are important here. If you are on M1 Macs (or other ARM variants), please also search for M1 in issues and see if the discussion there solves your problem.

(Basically, I am unable to reproduce this bug on Ubuntu or M1 Mac)

**Comment by gusgustavsohn** [comment]
I am also on a M1 Mac, suffering from the same problem. Whenever I try to open a PDF file, I get weird characters (which I assume is the PDF code) and the message 

`The epdfinfo server quit, restart it? (y or n)`

If I choose "y", nothing changes. If I choose "n", then I get another error:

`Error running timer 'pdf-cache--prefetch-start': (error "The epdfinfo server quit")`

FWIW, the pdf-tools-install worked ok, just showed 2 warnings but "Success". 

**What info should I provide for debugging this? I would be glad to help if this could be solved.**
