### ISSUE TITLE
Install pdf-tools in the old macos

### ISSUE THREAD

**Issue by flyingns** [vedang/pdf-tools#106]
My macos version is 10.14 and when I try to install `pdf-tools`, I need to install dependent `poppler` and `automake`, but `brew` doesn't succeed in installing `popper` due to the macos version being a bit old.

I successfully installed `poppler` via `macpor`t, but I couldn't recognize it in `brew`.

What will I do if I don't need to upgrade my macos to install `pdf-tools`?

Thank you.

**Comment by vedang** [comment]
You will need to modify the `./server/autobuild` script in `pdf-tools` to do this. You can search for `brew` in that file and change the code. That should solve your problem for you. If you need more help, please reply here again
