### ISSUE TITLE
Emacs throws errors when compiling `epdfinfo`

### ISSUE THREAD

**Issue by ywwry66** [vedang/pdf-tools#111]
When `epdfinfo` is recompiled, emacs signals errors:
```
File mode specification error: (error Buffer is not associated with any file :*compilation*)
error in process filter: Wrong type argument: markerp, nil [22 times]
```
However, these errors do not affect the compilation itself. Compilation will succeed and `pdf-tools` works as expected.

This does not happen for new installation of `pdf-tool`, only when `epdfinfo` is recompiled, for example, if `pdf-tools`/`poppler` is updated, or `endfinfo` is deleted manually.

My init file contains the following:
```
(use-package pdf-tools
  :magic ("%PDF" . pdf-view-mode)
  :init
  (setq TeX-view-program-selection '((output-pdf "PDF Tools"))) ; use pdf-tools with auctex
  (when (memq system-type '(darwin)) (setq pdf-view-use-scaling t)) ; retina display support for MacOS
  :config
  (bind-key "C-s" 'isearch-forward pdf-view-mode-map)
  (pdf-tools-install :no-query))
```

Thanks for looking into this.

**Comment by vedang** [comment]
Thank you for the report. It will take me some time to look into the problem, since I'm currently allocating time to closing out some long-pending PRs and it does not seem like critical breakage to me. It would be great if you can also share details of your system, specifically the OS and the version of `poppler` you have installed.

**Comment by ywwry66** [comment]
That's right it is not critical, so just take your time. This is actually not OS/poppler version dependent. It happens both on Windows and macOS for me. And this behavior dates back to when politza was the mainteiner.

**Comment by ywwry66** [comment]
After looking at this a little closer, I think it is not a `pdf-tools` bug, but rather a documentation issue (outdatedness) of `use-package`.

README of `use-package` takes `pdf-tools` as example usage of magic handlers:
```elisp
(use-package pdf-tools
  :load-path "site-lisp/pdf-tools/lisp"
  :magic ("%PDF" . pdf-view-mode)
  :config
  (pdf-tools-install :no-query))
```
However, this is no longer needed because `pdf-tools-install` and `pdf-loader-install` handle that automatically. For current version of `pdf-tools`, this configuration can be rewritten as
```elisp
(use-package pdf-tools
  :load-path "site-lisp/pdf-tools/lisp"
  :defer t
  :init
  (pdf-loader-install))
```
With this configuration, recompiling `epdfinfo` does not cause errors. Closing the issue.
