### ISSUE TITLE
Installation under MacOS - poppler error building PDF Tools server

### ISSUE THREAD

**Issue by rhstanton** [vedang/pdf-tools#116]
I'm running Emacs 28.1 under macOS 12.4. When installing pdf-tools, I get the error message below about poppler not being installed. Note that poppler IS installed and that

1) This all worked fine just a few weeks ago on the same machine. 

2) I've also tried running the command ```/Users/stanton/.emacs.d/straight/build/pdf-tools/build/server/autobuild -i /Users/stanton/.emacs.d/straight/build/pdf-tools/'``` at the command line, but this doesn't help.

Thanks for any suggestions:

```
-*- mode: compilation; default-directory: "~/.emacs.d/straight/build/pdf-tools/build/server/" -*-
Comint started at Tue May 31 11:17:02

/Users/stanton/.emacs.d/straight/build/pdf-tools/build/server/autobuild -i /Users/stanton/.emacs.d/straight/build/pdf-tools/
---------------------------
    Installing packages    
---------------------------
brew install pkg-config poppler automake
Warning: pkg-config 0.29.2_3 is already installed and up-to-date.
To reinstall 0.29.2_3, run:
  brew reinstall pkg-config
Warning: poppler 22.05.0 is already installed and up-to-date.
To reinstall 22.05.0, run:
  brew reinstall poppler
Warning: automake 1.16.5 is already installed and up-to-date.
To reinstall 1.16.5, run:
  brew reinstall automake

---------------------------
 Configuring and compiling 
---------------------------
./configure -q --bindir=/Users/stanton/.emacs.d/straight/build/pdf-tools/ && make clean && make -s
configure: error: Package requirements (poppler) were not met:

No package 'poppler' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables poppler_CFLAGS
and poppler_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
===========================
     Build failed.  ;o(    
===========================
Note: maybe try the '-d' option.

Comint exited abnormally with code 1 at Tue May 31 11:17:06
```

**Comment by chrischambers** [comment]
Not sure if this helps you directly @rhstanton, but it may help someone else resolve theirs, or perhaps @vedang  get to the root problem. In any case, the problems seem similar enough that I should put my solution here.

On my new M1 OSX 12.4 machine I had similar issues and had to do some manual intervention - I believe this could be related to the fact that M1 machines now use paths based around `/opt/homebrew` rather than `/usr/local`. My particular error messages were:

```
Package 'zlib', required by 'libpng', not found
```

and:

```
Package 'expat', required by 'fontconfig', not found
```

To successfully build, I ran the following commands:

```sh
brew install zlib expat
export PKG_CONFIG_PATH="/opt/homebrew/opt/zlib/lib/pkgconfig:/opt/homebrew/opt/expat/lib/pkgconfig"
```

`autobuild -i` then succeeded.

**Comment by vikram-mandyam** [comment]
See this also 
https://github.com/vedang/pdf-tools/issues/70#issuecomment-1109402390

**Comment by vedang** [comment]
Installation on M1 machines now works with no change required by the end-user. Please try to install `pdf-tools` from scratch, and re-open this ticket if installation fails.
