### ISSUE TITLE
simple syncing of position with orgmode text using isearch fails

### ISSUE THREAD

**Issue by fab6** [vedang/pdf-tools#117]
Hi,

for document and beamer presentation writing I am using extensively orgmode and would like to create a poor man's syncing based on frame titles in beamer.
The basic idea is to jump to the next header section and get the title into as the `isearch` entry and then go to `other-window` and use this string again as a `isearch` entry.

For this I was testing a bit this basic function from [http://xahlee.info/emacs/emacs/modernization_isearch.html](url) and extended it with one line to switch the window (second last line). This example searches just for the current word where the cursor is located:

```lisp
(defun xah-search-current-word-other-window ()
  "Call `isearch' on current word or text selection.
“word” here is A to Z, a to z, and hyphen 「-」 and underline 「_」, independent of syntax table.
URL `http://xahlee.info/emacs/emacs/modernization_isearch.html'
Version 2015-04-09"
  (interactive)
  (let ( $p1 $p2 )
    (if (use-region-p)
        (progn
          (setq $p1 (region-beginning))
          (setq $p2 (region-end)))
      (save-excursion
        (skip-chars-backward "-_A-Za-z0-9")
        (setq $p1 (point))
        (right-char)
        (skip-chars-forward "-_A-Za-z0-9")
        (setq $p2 (point))))
    (setq mark-active nil)
    (when (< $p1 (point))
      (goto-char $p1))
    (isearch-mode t)
    (other-window 1)
    (isearch-yank-string (buffer-substring-no-properties $p1 $p2))))
```
Unfortunately it seems that the search string is changed to some other encoding
For this example I was placed on a string `possibly` in the first window and this image shows the output of `isearch` in the pdf-mini-buffer:
![image](https://user-images.githubusercontent.com/3047695/173755068-9b327137-056b-4c0e-af39-f77cbabbe718.png)

Manually `isearch`ing and then switching the window to the pdf buffer works.

Does anyone have an idea how to fix this?
Thanks in advance!
Fab

**Comment by fab6** [comment]
btw, I would like to couple it with https://git.uni-wuppertal.de/firemod_UoW/tools/emacs/pdffire (which needs more description and robustness, but I use it daily)

**Comment by fbraennstroem-UoW** [comment]
A small update, I added this to pdfFire
```
(defun pdfFire-search-header-in-pdf-other-window()
  "Search for header in other window."
  (interactive)
  (let (
        (title-with-props (org-get-heading t))
        )
    (other-window 1)
    (isearch-forward nil t)
    (isearch-yank-string title-with-props)))
```
It works, but is obviously very simple. It searches only once in forward direction and does not remove any special keywords like TODO or priorities yet.

**Comment by fbraennstroem-UoW** [comment]
ok slightly enhanced```lisp
(defun pdfFire-search-header-in-pdf-other-window()
  "Search for header in other window."
  (interactive)
  (let (
        (title-with-props (org-get-heading t))
        (headingsL (org-heading-components))
        )
    (let (
          (title-no-props (nth 4 headingsL))
          )

      (other-window 1)
      (isearch-forward nil t)
      (isearch-yank-string title-no-props))))

```

**Comment by fab6** [comment]
This works better
```
(defun pdfFire-search-header-in-pdf-other-window()
  "Search for header in other window."
  (interactive)
  (let (
        (title-with-props (org-get-heading t))
        (headingsL (org-heading-components))
        )
    (let (
          (title-no-props (nth 4 headingsL))
          )

      (other-window 1)
      (isearch-forward nil t)
      (isearch-yank-string title-no-props))))
```
