### ISSUE TITLE
extend selection with shift-click

### ISSUE THREAD

**Issue by titaniumbones** [vedang/pdf-tools#12]
One thing I really miss in pdf-tools is the ability to modify the marked/selected region with shift-click.  So for instance, 

- I initially select some text to annotate (usually highlighting). 
- mouse selection in emacs is imprecise, and after releasing the mouse button, I realize I want to adjust the selection size.
- in  other programs, I could then press shift, depress the mouse button again, and adjust the size of the selection before releasing the button.

I can see there is something called "pdf-view-mouse-extend-region" which ought to be bound to C-<down-mouse-1> but I'm not sure it's exactly the same thing, and in any case in pgtk-emacs I can't seem t access that event (instead, on mouse release I get "C-<mouse-1> is not bound").  

Are you able to clarify as to whether the kind of selection extension/adjustment I'm looking for is possible? Thanks!

**Comment by vedang** [comment]
`pdf-view-mouse-extend-region` is indeed meant to do this and works correctly on my machine on Linux. Could you check on your end why you are getting the `not bound` error?

**Comment by titaniumbones** [comment]
Sorry, I had a laptop hard drive failure - I'll try to test this better when. I'm back on my feet!

**Comment by vedang** [comment]
Okay, closing this issue until then, feel free to reopen it if needed
