### ISSUE TITLE
No high resolution pdf on M1 Mac, sync and scrolling problems

### ISSUE THREAD

**Issue by todisorder** [vedang/pdf-tools#123]
Hello, first of all thanks for your work!

As described in [this reddit post I made](https://www.reddit.com/r/emacs/comments/vk2w18/problems_with_pdftools_auctex_on_mac_m1_blurry/), I'm having some trouble with pdf-tools on a brand new M1 Macbook with macOS 12.4. I am running emacs-mac 28.1 installed from homebrew, and I installed pdf-tools using the emacs interface, apparently with no issues. As you can see in my .emacs file, reproduced at the bottom, I have tried to include most of the fixes I could find on the internet, but to no avail. The main issues are:

1. Low resolution rendering of the pdf. Note that if I render it in DocView using `C-c C-c` on the pdf window, it *is* rendered in high resolution.
2. Syncing with the pdf only works from source to pdf. When trying from pdf to source, I get `C-<mouse-1> is undefined`.
3. Pages don't render properly (this happens also in DocView, so It may not be a pdf-tools problem): For instance, if I use `N` to advance the page after having scrolled using, e.g., `C-n`, the next page is not rendered until I scroll on it with the trackpad.
4. `(pdf-view-continuous t)` does not work.
5. Sometimes errors like `Wrong number of arguments (3.4) 2` appear in the minibuffer, for instance, while pressing `C-c C-c` on the pdf while in DocView mode; it does return to pdf-view mode but gives this error. 

I do have `(setq pdf-view-use-scaling t)` on my init file, as seen below.

I am not very knowledgeable, and this is my first issue ever I post on git, so thank you for your patience. I am just trying to undestand, basically, *whether the issues I'm having come from some error in my configuration (which is pretty minimal tbh), or if they are due to the fact that some things are still not adapted to the newer M1 macs*. 

Here is my .emacs file:

```
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(TeX-source-correlate-mode t)
 '(custom-enabled-themes '(deeper-blue))
 '(font-latex-fontify-script nil)
 '(package-selected-packages '(pdf-tools company))
 '(pdf-view-continuous t)
 '(pdf-view-max-image-width 14800)
 '(pdf-view-use-imagemagick nil)
 '(ring-bell-function 'ignore))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
(global-set-key (kbd "<backtab>") 'other-window)
(global-set-key (kbd "A-<backspace>") 'backward-kill-word)
(global-set-key (kbd "A-<left>") 'backward-word)
(global-set-key (kbd "A-<right>") 'forward-word)
(require 'reftex)
(add-hook 'LaTeX-mode-hook 'turn-on-reftex)
(add-hook 'latex-mode-hook 'turn-on-reftex)
(setq reftex-plug-into-auctex t)
(pdf-tools-install)
(setq TeX-view-program-selection '((output-pdf "PDF Tools"))
TeX-view-program-list '(("PDF Tools" TeX-pdf-tools-sync-view))
TeX-source-correlate-start-server t)
;; revert pdf-view after compilation
(add-hook 'TeX-after-compilation-finished-functions #'TeX-revert-document-buffer)
(setq pdf-view-use-scaling t)
;;(setq pdf-view-use-imagemagick nil)
(defun pdf-util-frame-scale-factor () 2)
(add-hook 'after-init-hook 'global-company-mode)
(add-to-list 'default-frame-alist '(height . 75))
(add-to-list 'default-frame-alist '(width . 120))

```

**Comment by ywwry66** [comment]
`pdf-tools` works fine on my M1 MacBook. Your issue of getting `C-<mouse-1> is undefined` suggests that `pdf-tools` is not loaded correctly. How did you install `pdf-tools`?

**Comment by todisorder** [comment]
I installed it using the emacs interface, with `list-packages`, etc. It did not give any errors as far as I can tell. Since it apparently worked at the time, I did not follow the more detailed macOS installation instructions in the README. The mac-specific instructions are below a line that says "The documentation below is only if you are installing from source, or for troubleshooting / debugging purposes.", so I'm confused whether I should follow them or not.
Can I ask **How did you install it?** Knowing it's possible to gives me hope. Thanks!

**Comment by ywwry66** [comment]
First, make sure your `poppler` is up to date. Run the following in terminal:
```
brew update
brew upgrade poppler
```

To get the most updated version of `pdf-tools`, add these lines to the top of your init file:
```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
```
Then restart Emacs, use `list-package` to reinstall `pdf-tools` from `melpa` repo (In the `list-package` buffer, there is a column called `Archive`, make sure it is `melpa`).

Check if these steps solves your issues, in particular the 2nd issue.

**Comment by todisorder** [comment]
My god, this worked!!!! Thank you so much!!! I'll write what I did for future reference: 

- I uninstalled pdf-tools from within emacs (not sure if it was necessary).
- Checked with brew if I had poppler already installed (I had, so nothing to do)
- Pasted your lines to my .emacs file.
- Indeed, now I can see two different versions of pdf-tools! installed the one from melpa. Before, I had the other one.
- It works perfectly now!

I would never have figured it out, as in the README it says "Installing this package via NonGNU ELPA or MELPA or any of the other package managers is straightforward and should just work." so I would never have thought of that, nor did I find your suggestion anywhere else. THANK YOU.

**Comment by vedang** [comment]
Thanks for your feedback @todisorder . I believe the version on NonGNU ELPA is older (because they only update when the `Version` header in the package is updated). I'm setting aside some time next weekend to cut a new release of `pdf-tools`, which I believe will make  `Installing this package via NonGNU ELPA or MELPA is straightforward and should just work` true again. 

Thank you for stepping in @ywwry66 ! I'm closing this issue.
