### ISSUE TITLE
Add feature: Jump to end of current page

### ISSUE THREAD

**Issue by bladrome** [vedang/pdf-tools#136]
Thanks for your great jobs on pdf tools, though there are much view features and bindings, I find that it's easy to jump to the beginning of the page(next page), but it's not easy to jump to the end of the current page under zoom.

**Comment by orgtre** [comment]
Try the image-mode commands listed in the [README](https://github.com/vedang/pdf-tools#view-and-navigate-pdfs). `image-eob` goes to the bottom right of the current page. If you just want to go straight down to the bottom you could pass a large line argument to `image-scroll-up`, like `(image-scroll-up 99999)`, as it will stop at the bottom. In [this issue](https://github.com/vedang/pdf-tools/issues/40) a few alternatives are discussed.

**Comment by bladrome** [comment]
Thank you @orgtre ! Great! Sorry I haven't read the docs enough.
