### ISSUE TITLE
epdinfo is creating all files with the execute bit set

### ISSUE THREAD

**Issue by znewman01** [vedang/pdf-tools#138]
See:

https://github.com/vedang/pdf-tools/blob/bb0b71f5bafd81d0b5647c4ec48fafa0bb6f6c21/server/epdfinfo.c#L357

Is there a reason? It's writing PNG files with `+x` to `/var/tmp` (on my Mac); executable files in temp directories are a little scary generally and my endpoint security scanner is raising alarm bells. Plus it doesn't seem like we need it.

**Comment by vedang** [comment]
It isn't necessary. Please submit a patch removing it, and I will merge it in (or wait for the end of this month, when I have set aside a weekend for working on `pdf-tools`
