### ISSUE TITLE
Problems with epdinfo.c:annotation_translate_quadrilateral

### ISSUE THREAD

**Issue by vizs** [vedang/pdf-tools#143]
Good day Vedang,

Andreas wrote the function annotation_translate_quadrilateral [1,2] to
fix misplaced annotations due to the then bug in glib.  This
misplacement bug can be seen in the images posted in issue
politza#577, along with PDFs in which the bug can be reproduced:
https://github.com/politza/pdf-tools/issues/577.

This lack of translation in the glib backend was fixed in poppler
0.86.0 but the workaround was still left hanging in epdfinfo.c which
brings us to today where this unneeded translation bites our back.
I commented out the calls to annotation_translate_quadrilateral in
epdinfo.c and to my surprise, there were no misplaced translations in
files which displayed the misplacing behaviour and in files which did
not have this behaviour.  What do you think about removing this
function, or only calling it in old poppler versions?

1. https://github.com/politza/pdf-tools/commit/0107f80dcf268d08ac075b01729820062c0fbd67
2. https://github.com/politza/pdf-tools/issues/122

P.S., If I was unclear, here's a patch to show what I mean

```
diff --git a/server/epdfinfo.c b/server/epdfinfo.c
index 770035d..bcdd868 100644
--- a/server/epdfinfo.c
+++ b/server/epdfinfo.c
@@ -1343,7 +1343,7 @@ annotation_markup_get_text_regions (PopplerPage *page, PopplerAnnotTextMarkup *a
       PopplerQuadrilateral *q = &g_array_index (quads, PopplerQuadrilateral, i);
       cairo_rectangle_int_t r;
 
-      annotation_translate_quadrilateral (page, q, FALSE);
+      /* annotation_translate_quadrilateral (page, q, FALSE); */
       q->p1.y = height - q->p1.y;
       q->p2.y = height - q->p2.y;
       q->p3.y = height - q->p3.y;
@@ -1398,7 +1398,7 @@ annotation_markup_append_text_region (PopplerPage *page, PopplerRectangle *regio
       q.p3.x = r->x1;
       q.p3.y = height - r->y2;
 
-      annotation_translate_quadrilateral (page, &q, TRUE);
+      /* annotation_translate_quadrilateral (page, &q, TRUE); */
       g_array_append_val (garray, q);
     }
   g_list_free (regions);
```

**Comment by vedang** [comment]
Thanks! I will remove this code in an upcoming commit. `poppler 0.86` is over 2.5 years old now, so I think it should be safe to get rid of this.

Leaving this issue open until I push the commit.
