### ISSUE TITLE
Allow for rotation of displayed pages

### ISSUE THREAD

**Issue by SterlingHooten** [vedang/pdf-tools#152]
Is there a way to rotate pages in the displayed buffer without mutating the original file?

This was called for twice in the previous repo with a suggestion for a solution at https://github.com/politza/pdf-tools/issues/89#issuecomment-657043167 but the request appears to have been closed in a bulk operation when moving to this repo.

This would be very useful, and is a feature in almost any other pdf viewer.

**Comment by vizs** [comment]
You can bind image-rotate in pdf-view-mode-map.  I have it bound to R.

**Comment by orgtre** [comment]
Yes, this works well for viewing. However, as soon as you do things like trying to add annotations, the image is reverted to its original orientation. An alternative for people that want to or are okay with modifying the original file is to use my qpdf wrapper [qpdf.el](https://github.com/orgtre/qpdf.el). Then calling the command `qpdf` and pressing `m` brings up some modification options, including page rotation.

**Comment by tongjie-chen** [comment]
Maybe we should keep an association list for the metadata of rotations.

**Comment by SterlingHooten** [comment]
> You can bind image-rotate in pdf-view-mode-map. I have it bound to R.

This worked for some pdfs, but I just ran into another type (not sure how to classify these) which gives the error
"No image under point". I'm not familiar enough with the internals of pdf-tools to know how these are being rendered differently.

**Comment by vizs** [comment]
24 Oct 2022, 22:53 by ***@***.***:

>
>
>
>
>>
>> You can bind image-rotate in pdf-view-mode-map. I have it bound to R.
>>
>>
>
>
> This worked for some pdfs, but I just ran into another type (not sure how to classify these) which gives the error
>  "No image under point". I'm not familiar enough with the internals of pdf-tools to know how these are being rendered differently.
>
>
>
Can you try out my linked PR in this issue?Message ID: ***@***.***>

**Comment by vedang** [comment]
I've merged @vizs 's PR #165 , which adds a convenient key-binding and functionality for rotation. Please try out the change in the latest pdf-tools.
