### ISSUE TITLE
Rebuild of epdfinfo: First do a make clean, to remove old library dependencies

### ISSUE THREAD

**Issue by johanwiden** [vedang/pdf-tools#16]
I recently had the problem that pdf-tools did not work, because epdfinfo depended on an old version of libpoppler.so, and that version was no longer available since I had upgraded the OS.
But rebuilding pdf-tools did not help: the rebuilt epdfinfo still depended on the old libpoppler.so.
After googling about this I got the answer that I had to cd into the pdf-tools build directory and there invoke 'make clean'.
I think it would be better if the pdf-tools build of epdfinfo started with doing a 'make clean'.

**Comment by ryanswilson59** [comment]
I have had the exact same issue on manjaro, this bug has caused a lot of difficulty with pdf-tools due to the update model of the OS.
