### ISSUE TITLE
dark-mode-minor-mode not working 

### ISSUE THREAD

**Issue by armindarvish** [vedang/pdf-tools#163]
Today, I started seeing an issue with the dark-mode. Basically, the pdf-view-dark-minor-mode does not have any effect on rendering. I can still right-click and use the rendering option to turn dark-mode on or off, but using the minor-mode just does not work! I am on MacOS, by the way.
 
You can see in the screenshots below with both "pdf-view-dark-minor-mode" equal to nil or t, the render setting is the same, and when I uncheck the render midnight option by mouse, it does not have any effect on the minor mode variable, either!

SC1: dark-minor-mode is t and render is dark
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/18317557/196511388-2742fdfc-61e0-4411-b090-fd63bd1637ae.png">

SC2: turned dark-minor-mode off but render is still dark
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/18317557/196511530-5ceae3db-f24b-463d-b2ee-38b15d82b92d.png">

SC3: used the context menu to uncheck the midnight option and render is light but the minor mode is unaffected!
<img width="1467" alt="image" src="https://user-images.githubusercontent.com/18317557/196511642-c6b31e1e-74d3-478e-b06b-a843cbb92e27.png">

**Comment by vedang** [comment]
I think what you are looking for is `M-x pdf-view-midnight-minor-mode`. 

Re: `pdf-view-dark-minor-mode`, the name does not make sense the way we think about dark-mode / light-mode today. It's meant specifically for PDFs which have dark backgrounds (instead of the white background that most PDFs have). I will look into improving documentation around it / renaming it in the future.

**Comment by armindarvish** [comment]
> I think what you are looking for is `M-x pdf-view-midnight-minor-mode`.
> 
> Re: `pdf-view-dark-minor-mode`, the name does not make sense the way we think about dark-mode / light-mode today. It's meant specifically for PDFs which have dark backgrounds (instead of the white background that most PDFs have). I will look into improving documentation around it / renaming it in the future.

Thanks for the quick response. Yes, that was it, I was confusing midnight-minor-mode with dark-minor-mode!
