### ISSUE TITLE
Builds always reinstall dependencies

### ISSUE THREAD

**Issue by MithicSpirit** [vedang/pdf-tools#17]
Building always reinstalls dependencies because in `have_packages_installed` it tries to compile with `cc` (line 170), however, `PDFDocEncoding.h` requires C++ as it attempts to `#include <string>`. This should be pretty easy to fix by replacing `cc` with `c++` on that line.
 https://github.com/vedang/pdf-tools/blob/d262cf9e19d57c6567e06e51d109150c20753839/server/autobuild#L156-L176

**Comment by vedang** [comment]
Thanks, I'll check the fix locally and merge it in over the weekend
