### ISSUE TITLE
How to change the dimensions or size of annotaions ?

### ISSUE THREAD

**Issue by pRot0ta1p** [vedang/pdf-tools#172]
Hi, is it possible to change the size of annotations? For example change the height of a highlight markup?

**Comment by vedang** [comment]
There is no straight-forward way to do this -- by which I mean there is no way to do it without reading and experimenting with `pdf-tools` code. You can look at `pdf-annot-default-annotation-properties` to see the default properties, and you can experiment by setting `pdf-annot-default-markup-annotation-properties` in your emacs config for different styles
