### ISSUE TITLE
org exporter hangs

### ISSUE THREAD

**Issue by deb75** [vedang/pdf-tools#184]
**Describe the bug**

Emacs 29.0.60 / mingw64 / latest pdf-tools

open and org file
export and open to pdf : C-c C-e l o
emacs hangs with message "Type C-c C-c to toggle between editing or viewing the document"
kill emacs is then the only solution

My pdf-tools configuration : 
```elisp
(require 'pdf-tools)
(add-hook 'doc-view-mode-hook 'pdf-tools-install)
```
and the related org configuration : 
```elisp
(delete '("\\.pdf\\'" . default) org-file-apps)
             (add-to-list 'org-file-apps '("\\.pdf\\'" . emacs))
```

Open with `C-x C-f` any pdf file works normally.

I disabled `org-pdftools`, the issue still persists

Regards

**Comment by vedang** [comment]
You don't need the `add-hook` command in your init. I don't know if it's causing any problems. My `pdf-tools` config is as follows: 

```elisp
(require 'pdf-tools)
(pdf-tools-install)
```

and I cannot reproduce this problem. Exporting and opening via `org-export` works correctly for me.

**Comment by vedang** [comment]
Please re-open the issue if the problem persists.

**Comment by deb75** [comment]
Thanks for your answer, I modified my `pdf-tools` configuration according to yours and it works just fine now.

Regards
