### ISSUE TITLE
pdf-tools-install fails on Void-Linux

### ISSUE THREAD

**Issue by isaacos** [vedang/pdf-tools#195]
**Describe the bug**
Running pdf-tools-install on a fresh install of Void-Linux fails an error that poppler-glib failed with cairo. I was able to resolve this issue by installing cairo-devel.

**Steps to Reproduce the behaviour**
Steps to reproduce the behaviour:
1. Start with a fresh install of Void-Linux glibc
2. Install emacs and pdf-tools on that version of emacs.
3. Run pdf-tools-install and confirm the package install

**What is the expected behaviour?**
Successful installation of pdf-tools

**Desktop**
Please complete the following information:

- OS: Void-linux
- Emacs Version: 28.2
- Poppler Version: I do not have poppler installed.

**Your pdf-tools install**
Please complete the following information:

- `pdf-tools` Version: 20230117.632 
- `pdf-tools` customization / configuration that you use I have no configuration at this point.

**Comment by vedang** [comment]
`cairo-devel` is now installed as part of the `autobuild` script, since dea468796d7a20c7b28bc4360d0663cb1dc010fd
