### ISSUE TITLE
Question: open issues here or politza?

### ISSUE THREAD

**Issue by workcomplete** [vedang/pdf-tools#2]
Apologies if this is a dull question (new to git, emacs) but I switched to this fork this week - best to open issues here or at politza/pdf-tools?

**Comment by vedang** [comment]
This is not a "dull" question at all :) 

I would very much prefer you open issues here, as I do not have control over closing issues in `politza/pdf-tools` (which is now unmaintained). Thank you for asking!

**Comment by vedang** [comment]
Closing this issue!
