### ISSUE TITLE
highlights difficult to see if midnight-mode enabled

### ISSUE THREAD

**Issue by 88-percent** [vedang/pdf-tools#202]
**Describe the bug**

    Highlights are barely visible in the new midnight-minor-mode 

**Steps to Reproduce the behaviour**
Steps to reproduce the behaviour:

    Open any pdf annotated with a highlight tool
    Enable midnight-minor-mode
    The highlights disappear, except for some faint tinting of the highlighted text

**What is the expected behaviour?**

    Highlighted text should remain clear and distinct

Desktop
Please complete the following information:

    OS: PopOS 22.04LTS
    Emacs Version: GNU Emacs 27.01 + Spacemacs

**Your pdf-tools install**
Please complete the following information:

    pdf-tools Version:  2021-11-10.513

pdf-tools customization / configuration that you use

    org-pdf-tools

**Additional context**

    Not sure if this is a bug or a feature request. The [recent update of midnight mode](https://github.com/vedang/pdf-tools/commit/fdb187493fe6f10fea31a76daa98c07db591cd90) is a fantastic improvement for those dealing with color documents. Not sure how feasible it is to add support for legible highlights given the current framework.

The attached screenshots hopefully help demonstrate the current issue:
1) how the pdf looks in Emacs without midnight mode enabled

![1-normal_mode](https://user-images.githubusercontent.com/41041011/224489530-06653b47-30e0-4f89-be01-97f4bd4e7958.png)

2) how the pdf looks in Emacs with midnight mode enabled

![2-midnight mode](https://user-images.githubusercontent.com/41041011/224489544-88cff523-67d9-44ab-9852-7a2887e03315.png)

3) the desired look where the highlight is obvious (taken from Evince with Night Mode enabled)

![3-Evince](https://user-images.githubusercontent.com/41041011/224489553-436e1f07-b2c2-4db5-b6d1-6b6c458a3130.png)

**Comment by Atreyagaurav** [comment]
I think the issue here is from the theme you're using instead of from the pdf-view, this is a screenshot from my setup. 

I have the wombat theme. Vanilla emacs.

![image](https://user-images.githubusercontent.com/46195892/228567096-98c149ae-56ec-49e1-9e5e-1c1b0715e77d.png)

**Comment by 88-percent** [comment]
OK, this is fantastic news! Your screenshot is exactly what I'm looking for.

Unfortunately, I can't reproduce it. 

It seems that changing my theme no longer effects pdf-view at all. No matter which theme I select, including wombat, I always get the same color scheme when viewing pdfs after invoking midnight mode.

I'm a bit lost as to where to go from here. Would you happen to know if this is something I should be asking about on a relevant Spacemacs forum, or might there be a change I could make to my dotfile to force pdf-view to adopt a specific theme?

**Comment by Atreyagaurav** [comment]
Maybe for now you can just not activate themed minor mode? I don't know what advantage it'd have, but if you want to retain the color lightness inversion, then that might be an option.
