### ISSUE TITLE
Make Error 127.

### ISSUE THREAD

**Issue by kulorro** [vedang/pdf-tools#205]
**Describe the bug**
make error 127.

**Steps to Reproduce the behaviour**
Steps to reproduce the behaviour:
1. Run ```cd /path/to/pdf-tools```
2. Run ```make -s```
3. See error ```Using Emacs 28.2
make: cask: No such file or directory
make: *** [Makefile:49: .cask/28.2] Error 127```

**Comment by vedang** [comment]
Please run `./server/autobuild` from the `pdf-tools` directory, and then run `make -s`. Let me know if this fixes the problem for you.

**Comment by pietroiusti** [comment]
I have the same problem too. Running `./server/autobuild` works, but `make -s` keeps giving the same error.

**Comment by pietroiusti** [comment]
> I have the same problem too. Running `./server/autobuild` works, but `make -s` keeps giving the same error.

Installing Cask (https://cask.readthedocs.io/en/latest/guide/installation.html) fixed the problem.
