### ISSUE TITLE
package description says pdf-tools won't work on windows

### ISSUE THREAD

**Issue by notuntoward** [vedang/pdf-tools#21]
The melpa package description says

> Note: This package requires external libraries and works currently only on GNU/Linux systems.

But the GitHub Readme says that it can work on MacOS and Windows -- and for me, on Windows, I can verify that it does work.

**Comment by vedang** [comment]
It works, but it is not supported. That is, if it stops working tomorrow, I will rely on the community to fix it. Hence the disclaimer. 

I will update the description to make this more clear
