### ISSUE TITLE
Feature request: highlight by selecting

### ISSUE THREAD

**Issue by asymmetric** [vedang/pdf-tools#212]
Currently, in order to highlight a piece of text I have to

1. select it
2. type the keybinding (`C-c C-a h`)

For such a common operation, I would prefer to skip the keyboard, and simply be in a mode whereby, whenever I select a piece of text, it gets highlighted.

Is this possible?

**Comment by ffsammak** [comment]
You can make it shorter by assigning a single key-binding to do highlighting after selecting your text/region:
I have this in my init.el to do this:

```
(use-package pdf-tools
  :bind
  (:map pdf-view-mode-map
    ;; normal isearch
	("C-s" . isearch-forward)
	;; custom keys
	("h" . pdf-annot-add-highlight-markup-annotation)
	("t" . pdf-annot-add-text-annotation)
	("D" . pdf-annot-delete))
...
)
```
