### ISSUE TITLE
Unknown render command: :selection-style

### ISSUE THREAD

**Issue by nanjigen** [vedang/pdf-tools#213]
**Describe the bug**
Getting `pdf-info-query: epdfinfo: Unknown render command: :selection-style` when attempting to select text with left mouse click. No text is selected.

**Steps to Reproduce the behaviour**
Steps to reproduce the behaviour:
1. Go to any pdf
2. Hold left mouse to select

**What is the expected behaviour?**
Text selection to occur

**Desktop**

- OS: Guix
- Emacs Version: GNU Emacs 28.1.90 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)
- Poppler Version: poppler-21.07.0

**Your pdf-tools install**

     Status: Available from melpa -- Install
    Archive: melpa
    Version: 20230404.327
     Commit: 7ff6293a25baaae65651b3e1c54b61208279a7ef
    Summary: Support library for PDF documents
   Requires: emacs-26.3, tablist-1.0, let-alist-1.0.4
    Website: https://github.com/vedang/pdf-tools/
   Keywords: files multimedia 
 Maintainer: Vedang Manerikar <vedang.manerikar@gmail.com>
     Author: Andreas Politz <mail@andreas-politz.de>

- `pdf-tools` customization / configuration that you use : turned off

**Comment by cyrilarnould** [comment]
I had the same problem using MSYS2's [`mingw-w64-emacs-pdf-tools-server`](https://packages.msys2.org/base/mingw-w64-emacs-pdf-tools-server) release, I think I figured it out. You're using the `melpa` version of the emacs package, but I guess you're using a (prebuilt?) binary for the `epdfinfo` executable which is built from tag 1.0.0.

So you have two options I guess: 

- Switch to the [`melpa-stable`](https://stable.melpa.org/#/pdf-tools) release of the emacs package (unfortunately, there's no highlighting at all in that version as far as I can tell)
- (re)build the epdfinfo executable yourself from the latest sources. This resolved the issue for me.

For users who rely on prebuilt binaries it would be nice if there were a new release of pdf-tools soon.

**Comment by vedang** [comment]
Oh interesting! I did not realise there were cases where people where using lisp code from one repository (melpa) and epdfinfo from another repository (melpa-stable)

I have 3 days in the next week cut out for pdf-tools work. At the end of the days, I will make a stable release so that the new changes propagate to melpa-stable as well.

**Comment by cyrilarnould** [comment]
> Oh interesting! I did not realise there were cases where people where using lisp code from one repository (melpa) and epdfinfo from another repository (melpa-stable)

I generally prefer melpa over melpa-stable as in some cases, packages take longer than major emacs releases to generate a new stable release and sometimes that includes great new features. 

The problem with the binary for me is that the integrated autogen rebuild flow didn't work on Windows. I guess I could have looked deeper into making it work but it was much easier to just get the prebuilt binary from MSYS2.

**Comment by barslmn** [comment]
I am having the same problem on doomemacs.
emacs: 28.2
pdf-tools package: 1.0.0
pdfinfo/poppler: 22.12
epdfinfo (debian apt): 1.0.0-1

**Comment by seokbeomKim** [comment]
Thanks @barslmn. Your workaround works well.
