### ISSUE TITLE
make: cask: No such file or directory

### ISSUE THREAD

**Issue by hongyi-zhao** [vedang/pdf-tools#214]
See my following testing:
```shell
$ git log -1
commit 7ff6293a25baaae65651b3e1c54b61208279a7ef (HEAD -> master, origin/master, origin/HEAD)
Author: Davide Masserut <dm@mssdvd.com>
Date:   Sun Apr 2 21:48:25 2023 +0200

    Ensure pixel-scroll-precision-mode deactivation
    
    Setting `pixel-scroll-precision-mode` to nil is not sufficient to disable
    the mode locally.
    
    Updates: #124

$ make -s
Using Emacs 30.0
make: cask: No such file or directory
make: *** [Makefile:49: .cask/30.0] Error 127
```

Then I run the steps [here](https://www.emacswiki.org/emacs/init-pdf-tools.el), but see the following chaos in pdf buffer: 

![image](https://user-images.githubusercontent.com/11155854/234312002-483d7c3c-7b0c-4a78-86ff-e16741868c48.png)

How to fix it?

Regards,
Zhao

**Comment by hongyi-zhao** [comment]
See [here](https://lists.gnu.org/archive/html/help-gnu-emacs/2023-04/msg00199.html) for more discussions:

> <h2>Re: use pdf-tools in Emacs.</h2>
> <hr>
> 
> 
> From: | Hongyi Zhao
> -- | --
> Subject: | Re: use pdf-tools in Emacs.
> Date: | Wed, 26 Apr 2023 10:01:24 +0800
> 
> 
> 
> 
> <hr>
> 
>

**Comment by vedang** [comment]
As explained in the thread, this bit of configuration works with `use-package`

```
(use-package pdf-tools
  :ensure t
  :init
  (pdf-tools-install))
```

I will add this to the documentation (or would really love a PR adding this to the README under the INSTALL section). Closing the ticket.

**Comment by hongyi-zhao** [comment]
In fact, [the current document](https://github.com/vedang/pdf-tools/blob/master/Installing%20pdf-tools) is break:

![image](https://user-images.githubusercontent.com/11155854/236622053-cac66629-e169-4f74-a4c1-61d5d3535be6.png)
