### ISSUE TITLE
Epdfinfo wrongly reports missing poppler library on Arch Linux

### ISSUE THREAD

**Issue by nameiwillforget** [vedang/pdf-tools#218]
**Describe the bug**
I just did an update of my Arch system and it seems to have broken comparability with `pdf-tools` as it can't display pdfs anymore and gives an error message:

```
File mode specification error: (error Error running ‘/usr/local/bin/epdfinfo’: /usr/local/bin/epdfinfo: error while loading shared libraries: libpoppler.so.126: cannot open shared object file: No such file or directory
)
```

**Steps to Reproduce the behaviour**
Try to open any pdf.

**What is the expected behaviour?**
`Pdf-tools` would display the pdf.

**Desktop**
- OS: Arch Linux with most recent updates
- Emacs Version: 28.2-2 
- Poppler Version: 23.05.0-1

**Your pdf-tools install**
     Status: Installed in ‘pdf-tools-20230117.632/’ (unsigned).
    Version: 20230117.632
     Commit: bc2ba117e8c3196ff9adf0da4fa1e63a8da3d7c8
    Summary: Support library for PDF documents

No further configuration.

![Screenshot from 2023-05-21 10-10-10](https://github.com/vedang/pdf-tools/assets/81373487/e7acb113-e538-4bd8-becc-4d345bfe50a0)

**Comment by sasinhe** [comment]
I second that, have you found any solutions?

**Comment by nameiwillforget** [comment]
> 

No.

**Comment by tongjie-chen** [comment]
Seems like the library's version has changed. Have you tried pdf-tools-install?

**Comment by vedang** [comment]
Closing this on the assumption that `pdf-tools-install` should fix it. Please re-open / file a new issue if required.
