### ISSUE TITLE
pdf-tools-install failed (popper)

### ISSUE THREAD

**Issue by sangkookchoi** [vedang/pdf-tools#245]
**Describe the bug**
When I run "pdf-tools-install" using Melpa, I'm getting the following error
---------------------

---------------------------
 Configuring and compiling 
---------------------------
autoreconf -i
configure.ac:14: installing './ar-lib'
configure.ac:11: installing './compile'
configure.ac:61: installing './config.guess'
configure.ac:61: installing './config.sub'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Makefile.am: installing './depcomp'
./configure -q --bindir=/Users/sangkookchoi/.emacs.d/elpa/pdf-tools-20230611.239/ && make clean && make -s
configure: error: Package requirements (poppler) were not met:

No package 'poppler' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables poppler_CFLAGS
and poppler_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
===========================
     Build failed.  ;o(    
===========================
Note: maybe try the '-d' option.

-----------------------------

**Desktop**
Please complete the following information:

- OS: macOS Sonoma 14.1.2
- Emacs Version: GNU emacs 29.1
- Poppler Version: stable 23.10.0 (bottled), HEAD
- pdf-tools version: pdf-tools-20230611.239

**Your pdf-tools install**
Please complete the following information:

- `pdf-tools` Version: [`M-x package-list-packages` -> Search for `pdf-tools` -> Hit Enter and copy all the details that pop up in the Help buffer]
- `pdf-tools` customization / configuration that you use

**Comment by ahmedwaqar** [comment]
I faced the same issue on Ubuntu 22.04. Try installing `sudo apt install libpoppler-dev libpoppler-glib-dev` and do `make -s`.

**Comment by sangkookchoi** [comment]
I reinstalled Homebrew and all the packages. Then it works now. Thanks

**Comment by sangkookchoi** [comment]
Done now
