### ISSUE TITLE
Jump back from a link.

### ISSUE THREAD

**Issue by MassimoLauria** [vedang/pdf-tools#259]
This is more a feature request than an issue. 

I'd like that whenever a link inside the PDF is clicked or followed (from a document to itself), I could then go back to the point I was before clicking. I was thinking about adding `xref-push-marker-stack` to `pdf-view-before-change-page-hook` but

- it seems not to do anything
- it would push a mark even when I am scrolling pages, which is not what I want.

Is there an easy solution/configuration I missed?

**Comment by bramadams** [comment]
Hi, does `pdf-history-backward` (bound to lowercase "l") work in this case?

**Comment by MassimoLauria** [comment]
Wow, thank you. I looked for this functionality in the docs, but I missed it. 
It works well.

**Comment by MassimoLauria** [comment]
I close the issue as solved.
