### ISSUE TITLE
Drop support for emacs < 26

### ISSUE THREAD

**Issue by thisch** [vedang/pdf-tools#26]
AFAICS emacs < 25 is not part of the continuous integration setup (the minimal emacs version tested in circleci is emacs-25; In the appveyor setup I can't find the versions of emacs that are tested: This seems to be the cmd used for installing emacs in appveyor: `bash -lc "pacman -S --needed --noconfirm mingw-w64-x86_64-emacs"`)

Dropping support for emacs < 25 would allow us to remove compatiblity code e.g. in pdf-view.el, which currently leads to a byte-compiler-warning (see #24).

**Comment by vedang** [comment]
This is planned for the v1.0.0 `pdf-tools` release. I'm currently in the process of cutting the v0.91 tag, which will be the last release to support Emacs 24.

**Comment by vedang** [comment]
Updating the title to reflect that we will now also drop support for Emacs 25. `pdf-tools` will support upto 3 major versions of Emacs, which as of this writing are 26, 27 and 28
