### ISSUE TITLE
Window manager might block pdf-view-mouse-set-region-rectangle / meta-drag

### ISSUE THREAD

**Issue by ckeschnat** [vedang/pdf-tools#262]
Hi,
not a bug report, just wanted to have a record in case someone else has this problem. So this can immediately be closed.

I saw the region selection mentioned[1], but it didn't work for me. Searching yielded no results and after a while I figured out that my window manager (openbox in this case) caught M-Left / pdf-view-mouse-set-region-rectangle.

I am not sure if M-Left is commonly bound by window managers, but there are also things like AltDrag[2] that might interfere.

[1] https://emacs.ch/@zyd/112051268286669588
[2] https://stefansundin.github.io/altdrag/

**Comment by vedang** [comment]
Thank you for creating the report! 🙏 , Closing!
