### ISSUE TITLE
obsolete outline commands in PDF Outline

### ISSUE THREAD

**Issue by rdiaz02** [vedang/pdf-tools#264]
**Describe the bug**
Using some commands in PDF Outline shows they are obsolete

**Steps to Reproduce the behaviour**
Steps to reproduce the behaviour:
1. `emacs -Q`
2. evaluate
```
(package-initialize)
(pdf-loader-install)

```
3. `find-file`  a pdf with table of contents (outline)  
4.  `o`  (for outline)
5. On the outline, type `a` , `Q` , `d`, `s`
6. See errors 

```
‘show-all’ is an obsolete command (as of 25.1); use ‘outline-show-all’ (C-c C-a) instead.
‘hide-sublevels’ is an obsolete command (as of 25.1); use ‘outline-hide-sublevels’ instead.
‘hide-subtree’ is an obsolete command (as of 25.1); use ‘outline-hide-subtree’ (C-c C-d) instead.
‘show-subtree’ is an obsolete command (as of 25.1); use ‘outline-show-subtree’ (C-c C-s) instead.
```

**What is the expected behaviour?**
No obsolete messages

**Desktop**

- OS: Debian GNU/Linux
- Emacs Version:   29.2.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.18.0) of 2024-01-20
- Poppler Version: 22.12.0-2+b1  

**Your pdf-tools install**
Please complete the following information:

- `pdf-tools` Version: 20230611.239, Commit: c69e7656a4678fe25afbd29f3503dd19ee7f9896
- `pdf-tools` customization / configuration that you use: none for the example above.

**Comment by rdiaz02** [comment]
PR in https://github.com/vedang/pdf-tools/pull/265

**Comment by vedang** [comment]
thanks, I'll merge it in!

**Comment by rdiaz02** [comment]
Thank you!

**Comment by vedang** [comment]
Please look through the comments I have posted to the PR @rdiaz02 and update the code 🙏 !
