### ISSUE TITLE
Memory leak worse than expected

### ISSUE THREAD

**Issue by port19x** [vedang/pdf-tools#279]
**Describe the bug**

#215 describes an issue with pdf-tools and it's image cache not freeing.
There are some tame, unverified causes and fixes made up there.
They do not tell the full story of the issue, so I'm making a seperate follow-up issue.

Most notably, the "fixes" of evaluating `(clear-image-cache)` or running `M-x pdf-cache-clear-data` only cut the problem in half.

**Steps to Reproduce the behaviour**

1. Go to a (preferably large) pdf file
2. Scroll down to the end
3. Try naive fixes
4. Still find fat remnants of data in memory

**What is the expected behaviour?**

All cache and data should be cleared when a pdf buffer is closed.
Opening a pdf and closing it should deterministically result in the same memory consumption as before

**Desktop**

- OS: Arch Linux
- Emacs Version: `GNU Emacs 29.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0)`
- Poppler Version: `24.03.0-1` (poppler-glib package)

**Your pdf-tools install**

- `20240429.407` / commit `30b505`
- from my [dotfiles](https://github.com/port19x/dotfiles): `(use-package pdf-tools            :config (pdf-tools-install))`

**Additional context**

The following screenshot contains detailed measurements of the issue.

![pdf-tools-bug-report](https://github.com/vedang/pdf-tools/assets/82055622/50952f73-2b03-4600-90bd-66e78cf1ea6b)

**Comment by aikrahguzar** [comment]
Mostly likely, this just means that Emacs is not returning memory to the OS. `M-x malloc-trim RET` might help with that, but there is not much `pdf-tools` can do.

**Comment by port19x** [comment]
That does help a whole bunch, but is still a bit confusing.
Is this how emacs memory management is supposed to work?
Is it appropiate to raise this issue to emacs-devel as a symptom of deeper troubles?
I just can't imagine that a good-citizen FOSS application not releasing memory is deemed acceptable by it's maintainers.

**Comment by aikrahguzar** [comment]
> That does help a whole bunch, but is still a bit confusing. Is this how emacs memory management is supposed to work? Is it appropiate to raise this issue to emacs-devel as a symptom of deeper troubles? I just can't imagine that a good-citizen FOSS application not releasing memory is deemed acceptable by it's maintainers.

I am not an expert but I think this is how memory management in general is supposed to work. Almost all software I use has trouble releasing memory. Firefox has the same behavior and I remember similar problems with okular years ago when I used it.

I think difficulties with releasing memory have been discussed on the mailing lists before so you should search for them and after reading them you can decide if you want to file a bug or not.

**Comment by aikrahguzar** [comment]
Anyhow the memory that is not released will be reused the next time Emacs needs it so unless you are pressed for RAM you shouldn't worry. If you are pressed for it you should make `image-cache-eviction-delay` smaller so that Emacs doesn't claim so much memory in the first place.

**Comment by port19x** [comment]
I guess I'll close this for now, having learned sth about emacs memory management

**Comment by aikrahguzar** [comment]
It turns out `pdf-tools` can do something about Emacs not claiming so much memory in the first place. I think if you apply this one line patch,
```diff
diff --git a/lisp/pdf-cache.el b/lisp/pdf-cache.el
index 980e4fc..4db4b85 100644
--- a/lisp/pdf-cache.el
+++ b/lisp/pdf-cache.el
@@ -451,7 +451,6 @@ WINDOW and IMAGE-WIDTH decide the page and scale of the final image."
                       (when (derived-mode-p 'pdf-view-mode)
                         (pdf-cache-put-image
                          page image-width data)
-                        (image-size (pdf-view-create-page page))
                         (pdf-util-debug
                           (message "Prefetched page %s." page))
                         (pdf-cache--prefetch-pages window image-width)))))))

```
the situation will improve.

I think the problem is with prefetching of pages and the diff above fixes that.  You can also disable `pdf-cache-prefetch-minor-mode` and see if it improves the situation.
