### ISSUE TITLE
pdf-tools not working on Windows

### ISSUE THREAD

**Issue by iago-pssjd** [vedang/pdf-tools#285]
1. I try to install it from Melpa. I have also `(use-package pdf-tools)` in .emacs, but pdf's open with DocView
2. I try to execute pdf-tools-install (https://www.reddit.com/r/emacs/comments/ywrrrq/how_to_run_pdfview_by_default_and_not_docview/) and I get asked: "Need to (re)build the epdfinfo program, do it now ? (y or n)"
2.1 If no, does not do anything and pdf-tools does not work yet
2.2 If yes,
```
---------------------------
    Installing packages    
---------------------------
pacman -S --needed base-devel
                      autoconf
                      automake
                      mingw-w64-x86_64-libpng
                      mingw-w64-x86_64-poppler
                      mingw-w64-x86_64-imagemagick
                      mingw-w64-x86_64-toolchain
                      mingw-w64-x86_64-openssl
                      mingw-w64-x86_64-zlib
error: mingw32: clave Â«5F944B027F7FE2091985AA2EFA11531AA0AA7F57Â» desconocida
:: Â¿Importar clave PGP 5F944B027F7FE2091985AA2EFA11531AA0AA7F57? [S/n] 
```
2.2.1 If no, it asks again
2.2.2 If yes (S)
```
error: no se pudo buscar la clave Â«5F944B027F7FE2091985AA2EFA11531AA0AA7F57Â» de forma remota
error: msys: clave Â«5F944B027F7FE2091985AA2EFA11531AA0AA7F57Â» desconocida
:: Â¿Importar clave PGP 5F944B027F7FE2091985AA2EFA11531AA0AA7F57? [S/n] 
```
what means that key could not be looked for remotely and asks again, and so on

**Comment by vedang** [comment]
Please let me know if you have gone through https://pdftools.wiki/d14e01ff and tried the steps mentioned there

**Comment by iago-pssjd** [comment]
No, I will try.

**Comment by iago-pssjd** [comment]
It worked. Thanks!
