### ISSUE TITLE
Can't install on windows

### ISSUE THREAD

**Issue by foogee** [vedang/pdf-tools#3]
(I posted this on politza's page but seeing from the other issue that things should be here, I've copied this over)

I followed the instructions on the README for installation and configuration on windows. I have mingw64 installed. I downloaded everything from https://github.com/politza/pdf-tools. Using mingw64, I cd to the path where I saved pdf-tools-master, and I run "make -s." I get the following:

```
$ make -s
Using Emacs 27.1
make: cask: No such file or directory
make: *** [Makefile:44: .cask/27.1] Error 127
```
When I try pdf-tools-install from emacs it asks whether I have msys2 installed and when I select yes it prompts me for the installation directory. I supply that info and then I get the following error:

```
---------------------------
 Configuring and compiling 
---------------------------
./configure -q --bindir=c:/Users/[name]/Documents/.emacs.d/elpa/pdf-tools-20200512.1524/ && make -s
configure: error: cannot find necessary  poppler-private header (see README.org)
===========================
     Build failed.  ;o(    
===========================
Note: maybe try the '-d' option.
```

Comint exited abnormally with code 1 at Mon Mar 15 10:16:29
Even though I have poppler installed through mingw64. This seems related to https://ask.csdn.net/questions/1704842, so I added the mingw64/bin directory to my path in hopes that that would resolve the issue, but it did not work.

Any ideas?

**Comment by vedang** [comment]
Please try installing cask as described here: https://github.com/cask/cask and then run `make -s` again in the `pdf-tools` directory. Let me know if that fixes the issue.

Also, please clone https://github.com/vedang/pdf-tools for the latest changes.

**Comment by foogee** [comment]
Thanks; I think that helped but I'm still stuck. I now get the new error message below, which suggests that cask-cli.el can't be found. But cask-cli.el absolutely is there in ~/.cask, so I have no idea why it can't find it. Do you have any further suggestions? 

And thanks much for your help. I'm so eager to get this set up! 

```
$ make -s
Using Emacs 27.1
Cannot open load file: No such file or directory, C:/Users/[name]/Documents/.cask/cask-cli.el
make: *** [Makefile:44: .cask/27.1] Error 255
```

**Comment by vedang** [comment]
Unfortunately, I am not a Windows user so I can't help much beyond pointing you to the docs. 

Double check that you have followed instructions here https://cask.readthedocs.io/en/latest/guide/installation.html#windows-installation-and-setup and that the file exists at `C:/Users/[name]/Documents/.cask/cask-cli.el` (and not for example at `C:/Documents/.cask/cask-cli.el`)

If you do figure it out, do come back and update the ticket!

**Comment by foogee** [comment]
O frabjous day! Callooh! Callay! That did it! thanks so much! I feel dumb for missing that.
