### ISSUE TITLE
Last visited position on PDF not remembered with save-place-mode

### ISSUE THREAD

**Issue by tjohnman** [vedang/pdf-tools#300]
**Describe the bug**
When reading a PDF with PDFView major mode and save-place-mode enabled, the last visited page is not restored on subsequent visits.

**Steps to Reproduce the behaviour**
Steps to reproduce the behaviour:
1. Hook pdf-view-mode to .pdf files.
2. Enable save-place-mode globally.
3. Visit PDF file and scroll down a few pages.
4. Kill the buffer.
5. Visit the same PDF file again.

**What is the expected behaviour?**
Upon visiting the file again, the user should on the same page where they left of.

**Desktop**
- OS: Windows 10
- Emacs Version: GNU Emacs 29.4 (build 2, x86_64-w64-mingw32) of 2024-07-05
- Poppler Version: 24.08

**Your pdf-tools install**
Please complete the following information:

- `pdf-tools` Version: 20240429.407
- `pdf-tools` customization / configuration that you use:
`(use-package pdf-tools
  :ensure t
  :mode ("\\.pdf\\'" . pdf-view-mode))`

**Comment by tjohnman** [comment]
Due to the nature of PDF rendering, I understand this might not be straightforward, but it would be nice to have a way to keep track of reading progress on PDF documents with or without relying on save-place.

**Comment by aikrahguzar** [comment]
There is https://github.com/nicolaisingh/saveplace-pdf-view
