### ISSUE TITLE
Select characters?

### ISSUE THREAD

**Issue by unhandyandy** [vedang/pdf-tools#307]
Is it possible to select, and highlight, characters that are less than a whole word?

For example, in "aardvark", is it possible to highlight just the 3rd "a"?

**Comment by aikrahguzar** [comment]
> Is it possible to select, and highlight, characters that are less than a whole word?
> 
> For example, in "aardvark", is it possible to highlight just the 3rd "a"?

Yes, this is controlled by `pdf-view-selection-style` which is `word` by default but you can set it to `glyph`.

**Comment by unhandyandy** [comment]
Thanks!
