### ISSUE TITLE
Is melpa repo updated?

### ISSUE THREAD

**Issue by techapu** [vedang/pdf-tools#32]
Hi! Thanks for all the work the mantainers have made! It is a relevant package...

I have a Guix SD linux distro. And I'm learning to configure it.
When I import the package from melpa, the only available one is politza/pdf-tools, am I correct? Or I am lost?

I use Emacs to read and edit a lot of legal content, and it is a little in org, laws in eww, or in nyxt, and a lot of PDF, mainly with pdf-tools.
I want to give this fork a try, because it is updated, and mantained (am I correct?)
Now I've installed Emacs 28.0.50 from the flatwhatson channel in Guix, and it gives me a lot of compilation warnings and that kind of stuff. I am not a professional coder.

Is there a canonical way to import this repository code to Guix with all the working dependencies? Will be in Melpa? If it is, what is the link? Thanks!

**Comment by techapu** [comment]
The package is working. I opened this as a way of knowing if it is my build or is it a general issue. And maybe update my repo data. In the readme I couldn't find any information related to new ways to transition from the politza repo to this. I'm sorry if I am lost.


It is a Linux 5.9.12-gnu #1 SMP 1 x86_64 GNU/Linux // Guix 1.3.// This is my emacs 28.0.50 output. 

Warning (comp): pdf-util.el:113:36: Warning: reference to free variable ‘image-mode-winprops-alist’ Disable showing Disable logging
Warning (comp): pdf-util.el:114:39: Warning: assignment to free variable ‘image-mode-winprops-alist’ Disable showing Disable logging
Warning (comp): pdf-util.el:335:58: Warning: reference to free variable ‘edges-left’ Disable showing Disable logging
Warning (comp): pdf-util.el:335:69: Warning: reference to free variable ‘region-left’ Disable showing Disable logging
Warning (comp): pdf-util.el:336:55: Warning: reference to free variable ‘region-width’ Disable showing Disable logging
Warning (comp): pdf-util.el:337:58: Warning: reference to free variable ‘edges-top’ Disable showing Disable logging
Warning (comp): pdf-util.el:337:68: Warning: reference to free variable ‘region-top’ Disable showing Disable logging
Warning (comp): pdf-util.el:338:55: Warning: reference to free variable ‘region-height’ Disable showing Disable logging
Warning (comp): pdf-util.el:339:58: Warning: reference to free variable ‘edges-right’ Disable showing Disable logging
Warning (comp): pdf-util.el:341:58: Warning: reference to free variable ‘edges-bot’ Disable showing Disable logging
Warning (comp): pdf-util.el:359:11: Warning: macro ‘pdf-util-with-edges’ defined too late Disable showing Disable logging
Warning (comp): pdf-util.el:717:39: Warning: reference to free variable ‘pdf-view-midnight-colors’ Disable showing Disable logging
Warning (comp): /home/techapu/.guix-profile/share/emacs/site-lisp/guix-emacs.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): pdf-util.el:663:22: Warning: the function ‘list-colors-duplicates’ is not known to be defined. Disable showing Disable logging
Warning (comp): pdf-info.el:1575:15: Warning: the function ‘pdf-util-frame-scale-factor’ is not known to be defined. Disable showing Disable logging
Warning (comp): pdf-util.el:512:8: Warning: the function ‘image-set-window-hscroll’ is not known to be defined. Disable showing Disable logging
Warning (comp): pdf-util.el:510:8: Warning: the function ‘image-set-window-vscroll’ is not known to be defined. Disable showing Disable logging
Warning (comp): pdf-util.el:330:29: Warning: the function ‘edges’ is not known to be defined. Disable showing Disable logging
Warning (comp): pdf-util.el:203:25: Warning: the function ‘pdf-view-current-page’ is not known to be defined. Disable showing Disable logging
Warning (comp): pdf-info.el:1460:23: Warning: the function ‘pdf-util-hexcolor’ is not known to be defined. Disable showing Disable logging
Warning (comp): /gnu/store/9mgmwrvwx7lkmpvn42fh5nqg0lcnks31-emacs-pdf-tools-0.90-1.c510442/share/emacs/site-lisp/pdf-tools-0.90-1.c510442/pdf-util.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): pdf-info.el:699:39: Warning: the function ‘pdf-view-buffer-file-name’ is not known to be defined. Disable showing Disable logging
Warning (comp): pdf-info.el:544:7: Warning: the function ‘pdf-util-munch-file’ is not known to be defined. Disable showing Disable logging
Warning (comp): pdf-info.el:477:23: Warning: the function ‘pdf-util-highlight-regexp-in-string’ is not known to be defined. Disable showing Disable logging
Warning (comp): /gnu/store/9mgmwrvwx7lkmpvn42fh5nqg0lcnks31-emacs-pdf-tools-0.90-1.c510442/share/emacs/site-lisp/pdf-tools-0.90-1.c510442/pdf-info.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): pdf-cache.el:339:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): pdf-cache.el:442:14: Warning: the function ‘pdf-view-desired-image-size’ is not known to be defined. Disable showing Disable logging
Warning (comp): pdf-cache.el:409:38: Warning: the function ‘pdf-view-create-page’ is not known to be defined. Disable showing Disable logging
Warning (comp): pdf-cache.el:390:30: Warning: the function ‘pdf-view-use-scaling-p’ is not known to be defined. Disable showing Disable logging
Warning (comp): pdf-cache.el:356:16: Warning: the function ‘pdf-view-current-page’ is not known to be defined. Disable showing Disable logging
Warning (comp): /gnu/store/9mgmwrvwx7lkmpvn42fh5nqg0lcnks31-emacs-pdf-tools-0.90-1.c510442/share/emacs/site-lisp/pdf-tools-0.90-1.c510442/pdf-cache.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): pdf-view.el:673:6: Warning: Unused lexical variable `pdf-view-inhibit-redisplay' Disable showing Disable logging
Warning (comp): pdf-view.el:885:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): pdf-view.el:907:1: Warning: Variable ‘pdf-view-inhibit-redisplay’ declared after its first use Disable showing Disable logging
Warning (comp): pdf-view.el:1166:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): pdf-view.el:1179:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): pdf-view.el:1196:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): pdf-view.el:1601:4: Warning: ‘registerv-make’ is an obsolete function (as of 27.1); Use your own type with methods on register-val-(insert|describe|jump-to) Disable showing Disable logging
Warning (comp): pdf-view.el:438:17: Warning: the function ‘cua-copy-region--pdf-view-advice’ is not known to be defined. Disable showing Disable logging
Warning (comp): pdf-view.el:341:15: Warning: the function ‘pdf-tools-pdf-buffer-p’ is not known to be defined. Disable showing Disable logging
Warning (comp): /gnu/store/9mgmwrvwx7lkmpvn42fh5nqg0lcnks31-emacs-pdf-tools-0.90-1.c510442/share/emacs/site-lisp/pdf-tools-0.90-1.c510442/pdf-view.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): pdf-misc.el:39:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): pdf-misc.el:44:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): pdf-misc.el:172:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): pdf-misc.el:183:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): pdf-misc.el:270:19: Warning: assignment to free variable ‘pdf-misc-print-program’ Disable showing Disable logging
Warning (comp): pdf-misc.el:276:19: Warning: the function ‘pdf-misc-print-program’ is not known to be defined. Disable showing Disable logging
Warning (comp): /gnu/store/9mgmwrvwx7lkmpvn42fh5nqg0lcnks31-emacs-pdf-tools-0.90-1.c510442/share/emacs/site-lisp/pdf-tools-0.90-1.c510442/pdf-misc.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): /gnu/store/9mgmwrvwx7lkmpvn42fh5nqg0lcnks31-emacs-pdf-tools-0.90-1.c510442/share/emacs/site-lisp/pdf-tools-0.90-1.c510442/pdf-tools.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): /gnu/store/2kgpcnjvvlxmacbgf46w4phzdpgb02bd-emacs-tablist-1.0/share/emacs/site-lisp/tablist-1.0/tablist-filter.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): pdf-isearch.el:130:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): pdf-isearch.el:214:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): /gnu/store/9mgmwrvwx7lkmpvn42fh5nqg0lcnks31-emacs-pdf-tools-0.90-1.c510442/share/emacs/site-lisp/pdf-tools-0.90-1.c510442/pdf-isearch.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): tablist.el:300:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): tablist.el:991:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): /gnu/store/2kgpcnjvvlxmacbgf46w4phzdpgb02bd-emacs-tablist-1.0/share/emacs/site-lisp/tablist-1.0/tablist.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): pdf-occur.el:356:55: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): pdf-occur.el:381:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): pdf-occur.el:417:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): /gnu/store/9mgmwrvwx7lkmpvn42fh5nqg0lcnks31-emacs-pdf-tools-0.90-1.c510442/share/emacs/site-lisp/pdf-tools-0.90-1.c510442/pdf-occur.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): pdf-history.el:47:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): /gnu/store/9mgmwrvwx7lkmpvn42fh5nqg0lcnks31-emacs-pdf-tools-0.90-1.c510442/share/emacs/site-lisp/pdf-tools-0.90-1.c510442/pdf-history.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): /gnu/store/2pny4z6mbi2aybgzzxz0yrzkds7hbpmq-emacs-org-9.4.6/share/emacs/site-lisp/org-9.4.6/org-compat.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): /gnu/store/2pny4z6mbi2aybgzzxz0yrzkds7hbpmq-emacs-org-9.4.6/share/emacs/site-lisp/org-9.4.6/org-macs.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): /gnu/store/2pny4z6mbi2aybgzzxz0yrzkds7hbpmq-emacs-org-9.4.6/share/emacs/site-lisp/org-9.4.6/org-keys.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): ol.el:1456:1: Warning: Variable ‘description’ left uninitialized Disable showing Disable logging
Warning (comp): /gnu/store/2pny4z6mbi2aybgzzxz0yrzkds7hbpmq-emacs-org-9.4.6/share/emacs/site-lisp/org-9.4.6/ol.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): org-table.el:501:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): org-table.el:1980:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): org-table.el:4686:29: Warning: the function ‘org-forward-paragraph’ is not known to be defined. Disable showing Disable logging
Warning (comp): /gnu/store/2pny4z6mbi2aybgzzxz0yrzkds7hbpmq-emacs-org-9.4.6/share/emacs/site-lisp/org-9.4.6/org-table.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): /gnu/store/2pny4z6mbi2aybgzzxz0yrzkds7hbpmq-emacs-org-9.4.6/share/emacs/site-lisp/org-9.4.6/ob-eval.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): org.el:4106:1: Warning: defconst `org-stamp-time-of-day-regexp' docstring wider than 80 characters Disable showing Disable logging
Warning (comp): /gnu/store/2pny4z6mbi2aybgzzxz0yrzkds7hbpmq-emacs-org-9.4.6/share/emacs/site-lisp/org-9.4.6/ob-core.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): /gnu/store/2pny4z6mbi2aybgzzxz0yrzkds7hbpmq-emacs-org-9.4.6/share/emacs/site-lisp/org-9.4.6/ob-emacs-lisp.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): org.el:10395:13: Warning: reference to free variable ‘org-log-setup’ Disable showing Disable logging
Warning (comp): /gnu/store/2pny4z6mbi2aybgzzxz0yrzkds7hbpmq-emacs-org-9.4.6/share/emacs/site-lisp/org-9.4.6/org-entities.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): org.el:15631:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): /gnu/store/2pny4z6mbi2aybgzzxz0yrzkds7hbpmq-emacs-org-9.4.6/share/emacs/site-lisp/org-9.4.6/org-faces.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): org.el:8127:11: Warning: the function ‘org-element-extract-element’ is not known to be defined. Disable showing Disable logging
Warning (comp): org.el:8112:16: Warning: the function ‘org-element-insert-before’ is not known to be defined. Disable showing Disable logging
Warning (comp): org.el:8106:7: Warning: the function ‘org-element-map’ is not known to be defined. Disable showing Disable logging
Warning (comp): org.el:8105:20: Warning: the function ‘org-element-restriction’ is not known to be defined. Disable showing Disable logging
Warning (comp): org.el:8104:17: Warning: the function ‘org-element-parse-secondary-string’ is not known to be defined. Disable showing Disable logging
Warning (comp): /gnu/store/2pny4z6mbi2aybgzzxz0yrzkds7hbpmq-emacs-org-9.4.6/share/emacs/site-lisp/org-9.4.6/org.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): org-list.el:2305:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): /gnu/store/2pny4z6mbi2aybgzzxz0yrzkds7hbpmq-emacs-org-9.4.6/share/emacs/site-lisp/org-9.4.6/org-list.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): /gnu/store/2pny4z6mbi2aybgzzxz0yrzkds7hbpmq-emacs-org-9.4.6/share/emacs/site-lisp/org-9.4.6/org-pcomplete.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): /gnu/store/2pny4z6mbi2aybgzzxz0yrzkds7hbpmq-emacs-org-9.4.6/share/emacs/site-lisp/org-9.4.6/ob-comint.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): org-src.el:672:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): /gnu/store/2pny4z6mbi2aybgzzxz0yrzkds7hbpmq-emacs-org-9.4.6/share/emacs/site-lisp/org-9.4.6/org-src.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): /gnu/store/2pny4z6mbi2aybgzzxz0yrzkds7hbpmq-emacs-org-9.4.6/share/emacs/site-lisp/org-9.4.6/org-footnote.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): /gnu/store/2pny4z6mbi2aybgzzxz0yrzkds7hbpmq-emacs-org-9.4.6/share/emacs/site-lisp/org-9.4.6/org-macro.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): /gnu/store/2pny4z6mbi2aybgzzxz0yrzkds7hbpmq-emacs-org-9.4.6/share/emacs/site-lisp/org-9.4.6/ob-exp.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): /gnu/store/2pny4z6mbi2aybgzzxz0yrzkds7hbpmq-emacs-org-9.4.6/share/emacs/site-lisp/org-9.4.6/ob-table.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): /gnu/store/2pny4z6mbi2aybgzzxz0yrzkds7hbpmq-emacs-org-9.4.6/share/emacs/site-lisp/org-9.4.6/ob-lob.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): /gnu/store/2pny4z6mbi2aybgzzxz0yrzkds7hbpmq-emacs-org-9.4.6/share/emacs/site-lisp/org-9.4.6/ob-ref.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): /gnu/store/2pny4z6mbi2aybgzzxz0yrzkds7hbpmq-emacs-org-9.4.6/share/emacs/site-lisp/org-9.4.6/ob-tangle.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): pdf-links.el:105:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): pdf-links.el:372:4: Warning: ‘org-open-link-from-string’ is an obsolete function (as of Org 9.3); use ‘org-link-open-from-string’ instead. Disable showing Disable logging
Warning (comp): /gnu/store/9mgmwrvwx7lkmpvn42fh5nqg0lcnks31-emacs-pdf-tools-0.90-1.c510442/share/emacs/site-lisp/pdf-tools-0.90-1.c510442/pdf-links.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): pdf-outline.el:136:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): pdf-outline.el:187:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): /gnu/store/9mgmwrvwx7lkmpvn42fh5nqg0lcnks31-emacs-pdf-tools-0.90-1.c510442/share/emacs/site-lisp/pdf-tools-0.90-1.c510442/pdf-outline.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): pdf-sync.el:118:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): pdf-sync.el:540:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): /gnu/store/9mgmwrvwx7lkmpvn42fh5nqg0lcnks31-emacs-pdf-tools-0.90-1.c510442/share/emacs/site-lisp/pdf-tools-0.90-1.c510442/pdf-sync.el: Error: File error Opening output file Disable showing Disable logging
Warning (comp): pdf-annot.el:163:1: Warning: custom-declare-variable `pdf-annot-latex-header' docstring wider than 80 characters Disable showing Disable logging
Warning (comp): pdf-annot.el:322:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): pdf-annot.el:1422:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): pdf-annot.el:1774:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' Disable showing Disable logging
Warning (comp): /gnu/store/9mgmwrvwx7lkmpvn42fh5nqg0lcnks31-emacs-pdf-tools-0.90-1.c510442/share/emacs/site-lisp/pdf-tools-0.90-1.c510442/pdf-annot.el: Error: File error Opening output file Disable showing Disable logging

**Comment by vedang** [comment]
Hi @techapu 

These warnings can be safely ignored. I have a low priority task to remove compilation warnings from `pdf-tools`, and thanks for the detailed log, but these do not affect the functionality in any way.

And yes, this is the maintained fork of the project. 

Thanks!
