### ISSUE TITLE
Release v0.91

### ISSUE THREAD

**Issue by abcdw** [vedang/pdf-tools#33]
Hi, thank you very much for maintaining and improving this package.

Can you make a new tag, please? So downstream package managers will be more willing to update pdf-tools package.

I'll send a patch to GNU Guix.

Keep up great work!)

**Comment by vedang** [comment]
Hey @abcdw , 

I was thinking of making some more changes before cutting a tag. However, if this is blocking adoption / upgrade in some way, I will cut a new tag for `pdf-tools`. I will need around 2 weeks to get to it though, so expect it to be done by mid-July. 

Thanks,
Vedang

**Comment by abcdw** [comment]
Vedang Manerikar writes:

> I was thinking of making some more changes before cutting a
> tag. However, if this is blocking adoption / upgrade in some way, I
> will cut a new tag for `pdf-tools`. I will need around 2 weeks to get
> to it though, so expect it to be done by mid-July.

Sure, take your time!)

I already updated a package recipe for Guix and now it tracks 5f77da,
but would be great to use a tag instead of a commit, once you finish
with the release.

Thank you for your work, see you!)

**Comment by vedang** [comment]
Closing this ticket, a v0.91 release has been cut and we are on our way to v1.0.0 and v1.1.0 releases (planned for Apr, 2022)

**Comment by abcdw** [comment]
On 2022-01-05 22:31, Vedang Manerikar wrote:

> Closing this ticket, a v0.91 release has been cut and we are on our
> way to v1.0.0 and v1.1.0 releases (planned for Apr, 2022)

The package in a Guix repository was updated to this version.
https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/emacs-xyz.scm?id=9d613c36de1ea52e745d30bad841b6cdeaca65f4#n3329

Thank you very much!

-- 
Best regards,
Andrew Tropin
