### ISSUE TITLE
Ambigious behaviour in embedded image

### ISSUE THREAD

**Issue by utkarsh181** [vedang/pdf-tools#47]
Hi Vedang,

Currently I am facing a really strange bug related to pdf-tools
underlying rendering engine.  Steps to reproduce the bug:

1. Open sample.pdf
2. Press `<f11>` to maximize Emacs.  Currently you will notice a diamond
in Figure 5.2 which represents a conditional.
3. Again press `<f11>` to un-maximize Emacs.  Diamond disappears!

System information:

1. Emacs version: 28.0.50
2. OS: GNU/Linux
3. Linux version: 5.14.7-arch1-1
4. Poppler version: 21.09.0-1
5. pdf-tools version: 20210531.1613

[sample.pdf](https://github.com/vedang/pdf-tools/files/7263969/sample.pdf)

**Comment by vedang** [comment]
This works perfectly fine on my end.

Check if you can move around in the sample file and see the flowchart (using `up`, `down` keys or using `M-x image-eob` and `M-x image-bob`)

Closing this ticket, please re-open it with new info if any.
