### ISSUE TITLE
scrolling doesn't work well with pixel-scroll-precision-mode

### ISSUE THREAD

**Issue by seagle0128** [vedang/pdf-tools#56]
Recently Emacs 29 introduces a new feature pixel scrolling, but it doesn't work in pdf-tools. I talked to the author of `pixel-scroll-precision-mode`, and he thought it might be an issue of `pdf-tools`.

**Comment by vedang** [comment]
I'll need to investigate the new changes before I can comment on this. Unfortunately, I'm short on time right now, so it would be great if someone reading this can investigate further.

**Comment by mtreca** [comment]
Also see #37
