### ISSUE TITLE
Add native support for Wayland when Emacs is compiled with pgtk

### ISSUE THREAD

**Issue by pati-ni** [vedang/pdf-tools#67]
Experimental pgtk support has been merged in recent emacs versions.

Is it possible to build pdf-tools run natively in Wayland environments instead of XWayland without a complete overhaul?

**Comment by vedang** [comment]
I have no experience with Wayland, so I can't estimate this off the top of my head. I'll track it as a feature request and get back to it as and when possible.

**Comment by vizs** [comment]
If I'm not mistaken or doing something incorrectly, there isn't need for any extra work.  To test if pdf-tools works without Xwayland, I did the following (inside Xorg though):

```
cage -- env DISPLAY= emacs
```

then opened a pdf file in that instance.

(pgtk-backend-display-class) => "GdkWaylandDisplay" so I don't think any XWayland stuff creeped in.  To be absolutely sure, I ran sxiv from the Emacs instance running inside cage which failed with "sxiv: Error opening X display".

**Comment by pati-ni** [comment]
> If I'm not mistaken or doing something incorrectly, there isn't need for any extra work. To test if pdf-tools works without Xwayland, I did the following (inside Xorg though):
> 
> ```
> cage -- env DISPLAY= emacs
> ```
> 
> then opened a pdf file in that instance.
> 
> (pgtk-backend-display-class) => "GdkWaylandDisplay" so I don't think any XWayland stuff creeped in. To be absolutely sure, I ran sxiv from the Emacs instance running inside cage which failed with "sxiv: Error opening X display".

@vizs Looks like you are right. I noticed some blurry fonts in my HiDPI display so I figured it should be Xwayland. It looks like I was wrong, since I can not an associated X client with the buffer.

I will try to reproduce the blurry fonts and open another issue if need be.

**Comment by vedang** [comment]
For blurry fonts on hidpi, make sure you are  using scaling.

`(setq pdf-view-use-scaling t)`

 Ref: https://pdftools.wiki/20ef86be

**Comment by rommeswi** [comment]
The font scaling is so important, it should be activated by default! It makes a huge difference.
