### ISSUE TITLE
Error building the server: `\r\n` line endings and bad interpreter

### ISSUE THREAD

**Issue by Phundrak** [vedang/pdf-tools#7]
As reported in [this PR](https://github.com/syl20bnr/spacemacs/pull/14644) which will hopefully bring this fork to Spacemacs, I noticed while building the server the following errors:
- Emacs reports
  ```
  /home/phundrak/.emacs.d/elpa/28.0/develop/pdf-tools-20210411.1603/build/server/autobuild -i /home/phundrak/.emacs.d/elpa/28.0/develop/pdf-tools-20210411.1603/
  /usr/bin/sh: /home/phundrak/.emacs.d/elpa/28.0/develop/pdf-tools-20210411.1603/build/server/autobuild: /bin/sh^M: bad interpreter: No such file or directory
  ```
- While running directly `autobuild` from the shell gives the following error:
  ```
  Failed to execute process './autobuild'. Reason:
  The file uses windows line endings (\r\n). Run dos2unix or similar to fix it.
  ```

I see two issues here:
1. The incorrect line endings
2. The use of `/bin/sh`.

Regarding the second issue, I think it would be safer to directly refer the shell to `bash` and not `sh`, since the latter can be symlinked to various shells depending on the OS, and not necessarily POSIX-compliant ones. `bash` on the other hand is present on most UNIX and POSIX systems, including macOS.

I will try to submit a PR soon to fix at least the first issue.

**Comment by lebensterben** [comment]
- You should never use bash. Some system have dash instead of bash.
- You should never use /bin/sh and always /usr/bin/env sh. /bin is never the standard path according to Linux Filesystem Specification.

**Comment by Phundrak** [comment]
Alright, so here’s the weird thing, when I clone locally the repo
through git, `autobuild` actually has LF line endings, not CRLF. Running
`dos2unix` does nothing, and Emacs indicates LF line endings too, so
nothing I can modify. But, if I let Emacs (Spacemacs) download the
package itself, I get a file with CRLF line endings. Maybe this is an
issue from Spacemacs’ package manager?

> * You should never use bash. Some system have dash instead of bash.
Fair enough, I did not know about dash.

> * You should never use /bin/sh and always /usr/bin/env sh. /bin is never
>  the standard path according to Linux Filesystem Specification.
Also true, this at least should be changed.

**Comment by vedang** [comment]
I don't think the line-ending problem is a `pdf-tools` problem. I'd appreciate it if users of `spacemacs` could investigate this on their end. 

Re: changing the shebang line, I will create a separate issue to track this, I see it as a low hanging fruit and would love to accept a PR for it.

**Comment by vedang** [comment]
I've confirmed that all files in `pdf-tools` have the correct line endings, and have created an issue to track the #! change. Closing this ticket.
