### ISSUE TITLE
Newly compiled version cannot open PDFs

### ISSUE THREAD

**Issue by mtreca** [vedang/pdf-tools#84]
I recently updated my homebrew packages and MELPA Emacs libraries on MacOS 12.2.1 and Emacs 27.2.
I was able to compile epdfinfo without issues (albeit with a small number of warnings). However, I noticed two changes:

1. I have the following instruction in the use-package declaration for pdf-tools:

```elisp
(use-package pdf-tools
  :ensure t
  :mode "\\.pdf\\'"
  :init (pdf-loader-install))
```

The `pdf-loader-install` would only trigger when the package was updated. It is now triggered everytime I open a PDF document.

2. Whenever I open a PDF file, I get the following stacktrace:

```
Debugger entered--Lisp error: (wrong-type-argument stringp number-or-marker-p)
  string-match(":Document is encrypted\\'" number-or-marker-p nil)
  pdf-info-encrypted-p()
  pdf-view-decrypt-document()
  pdf-view-mode()
  pdf-tools-install-noverify()
  #f(compiled-function (executable) #<bytecode 0x479377ff>)("/Users/mtreca/.config/emacs/elpa/pdf-tools-2022021...")
  #f(compiled-function (buffer status) #<bytecode 0x4ecd0531>)(#<buffer *compilation*> "finished\n")
  run-hook-with-args(#f(compiled-function (buffer status) #<bytecode 0x4ecd0531>) #<buffer *compilation*> "finished\n")
  compilation-handle-exit(exit 0 "finished\n")
  compilation-sentinel(#<process comint> "finished\n")
```

Interestingly, the PDF files I try to open are not encrypted.

Any idea on what is going wrong?

**Comment by mtreca** [comment]
Final update. Entirely uninstalling and reinstalling homebrew did the trick for some reason. Sorry for the noise.

**Comment by vedang** [comment]
No worries, thank you for capturing your process here, it will be helpful to others.
