### ISSUE TITLE
Text selection lag

### ISSUE THREAD

**Issue by workcomplete** [vedang/pdf-tools#87]
I wanted to link this issue from the previous maintainer's page because as far as I can tell no solution was reached. I am personally still dealing with lag when selecting text and I suspect others might be as well:

https://github.com/politza/pdf-tools/issues/235#issue-186257910 #

Is this likely to be an enhancement on the horizon?

**Comment by vedang** [comment]
Once I clean up some low-hanging work, I plan to focus on improving `pdf-tools` annotations support. This bug may be tangentially picked up / addressed at that time. My plan is to do this in July. Thanks for opening an issue here as it's easier for me to track it this way.

**Comment by jingxlim** [comment]
Hello. I wanted to add my frustration with this issue. I really want pdf-tools to be my daily pdf-viewing driver for reading pdfs but this is proving to be very difficult because I rely on highlights a lot. Thanks!

**Comment by JonatanSahar** [comment]
same here, it's still a major usability issue...

**Comment by sati-bodhi** [comment]
+1 to fix selection lag issue.

**Comment by vedang** [comment]
Marking this issue as closed.

Thanks to the stellar work by @hrdl-github in #73, we have now changed the default unit of selection from `glyph` to `word`. This speeds up selection significantly. Please install the latest version of `pdf-tools` and try it out (wait about 6 hours from the time of this comment to ensure that MELPA gets updated). 

Look at the documentation of `pdf-view-selection-style` for more information.

**Comment by vedang** [comment]
Re: Adding support for more markup styles, I'd like to continue tracking it in the issue @sati-bodhi has created for it, which is #179 . I've been meaning to get around to improving annot support, but I cannot find the time for it. PRs would be great!
