### ISSUE TITLE
Feature request: add support for `clone-indirect-buffer` (or alternative)

### ISSUE THREAD

**Issue by matthuszagh** [vedang/pdf-tools#88]
I often find that I need to simultaneously view two different pages of a PDF. Emacs has `clone-indirect-buffer`, but unfortunately this is currently incompatible with pdf-tools (see https://github.com/politza/pdf-tools/issues/281, https://github.com/politza/pdf-tools/issues/132, and [Emacs StackExchange: pdf-tools indirect buffers](https://emacs.stackexchange.com/questions/32542/pdf-tools-indirect-buffers/32547#32547)). Apparently, the underlying issue is that indirect buffers don't have `buffer-file-name` set. It would be great if there was some way to achieve this functionality, even if it required using something other than `clone-indirect-buffer`.

**Comment by orgtre** [comment]
What would be the advantage over just using one of the `split-window-`functions? In any case it seems that all that is required is reloading pdf-view-mode, which can be achieved like this:
```lisp
(defun my-pdf-view-mode-reload ()
  (when (equal major-mode 'pdf-view-mode)
    (pdf-view-mode)))

(add-hook 'clone-indirect-buffer-hook 'my-pdf-view-mode-reload)
```

**Comment by matthuszagh** [comment]
@orgtre Splitting a window from a PDF just shows the same PDF buffer in two different windows. These are not sufficiently disassociated. For example, changing the size of one PDF also changes the size of the other (with `pdf-view-fit-width-to-window` or similar). Invoking `(pdf-view-mode)` in one buffer also doesn't avoid this problem.

**Comment by orgtre** [comment]
I see. For me `clone-indirect-buffer` works as expected after applying the above fixes, but if that doesn't work for you I guess further research is needed.

**Comment by matthuszagh** [comment]
My mistake, your fix *does* work for me. Thanks! I'm closing this as I feel it's an adequate solution. It can be reopened if anyone encounters any limitations.
